INSERT INTO role VALUES (DEFAULT, 'role_user');
INSERT INTO role VALUES (DEFAULT, 'role_admin');
INSERT INTO user VALUES (DEFAULT, FALSE, 'administrator', 'admin@mail.com');
INSERT INTO user_roles VALUES (1, 2);
INSERT INTO product VALUES (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board'),
                           (DEFAULT, 55, 'vc', 5000, 'Video card'),
                           (DEFAULT, 55, 'cpu proc', 5034, 'CPU'),
                           (DEFAULT, 55, 'hard drive',  2123, 'HDD'),
                           (DEFAULT, 55, 'memory',  3423, 'RAM'),
                           (DEFAULT, 55, 'monitor',  4566, 'Monitor'),
                           (DEFAULT, 55, 'keyboard',  2342, 'Keyboard'),
                           (DEFAULT, 55, 'mouse',  123, 'Mouse'),
                           (DEFAULT, 55, 'sdd flush',  6754, 'SSD'),
                           (DEFAULT, 55, 'cooler',  444, 'Cooler'),
                           (DEFAULT, 55, 'mother board',  1234, 'Mother board');




